config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'errors/not_found'
  get 'errors/internal_server_error'
  root 'sessions#home'
  get '/' => 'sessions#home'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users
  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all
  
  get 'product_lines/new'
  resources :product_lines do
    collection { post :import }
  end
  
  get 'health_concerns/new'
  resources :health_concerns do
    collection { post :import }
  end
  
  get 'health_concerns/concerns' => 'health_concerns#concerns'
  post 'health_concerns/concerns' => 'health_concerns#create'

  get 'product_line' => 'health_concerns#product_line'
  get 'product_category' => 'health_concerns#product_category'
  get 'company' => 'health_concerns#company'
  get 'show' => 'health_concerns#show'
  get 'cart'  => 'health_concerns#update_cart'
  get 'final_cart' => 'health_concerns#final_cart'
  get 'return' => 'health_concerns#continue'
  get 'modify_cart' => 'health_concerns#modify_cart'
  resources :password_resets
end

app/models/health_concern.rb
class HealthConcern < ApplicationRecord
    belongs_to :user
  def self.update_table(user_id,calorie_healthy,heart_healthy,sodium_friendly,carb_friendly,kidney_friendly)
     begin
       user_concerns_header = ["user_id","Calorie_Friendly","Heart_Healthy", "Sodium_Friendly","Carb_Friendly","Kidney_Friendly"]
       user_row = HealthConcern.find_by user_id: user_id
       user_concerns = Hash[[user_concerns_header, [user_id,calorie_healthy,heart_healthy,sodium_friendly,carb_friendly,kidney_friendly]].transpose]
       if !user_row
         user_row = HealthConcern.create user_concerns
       else
         user_row.update_attributes user_concerns
       end
     end
  end
end

app/controllers/health_concerns_controller.rb
class HealthConcernsController < ApplicationController

  before_action :logged_in_user, only: [:new,:index,:import,:concerns,:create,:product_line,:product_line_create]
  before_action :is_admin, only: [:new, :index, :import]
  @to_remove = []
  def new

  end
  
  def product_line
    
  end
  
  def index
    
  end
  
  def continue
    redirect_to '/product_line'
  end
  
  def update_cart
    begin
      p_id = params[:compny]
      if p_id !=nil
        UserCart.update_cart(current_user.id,p_id.to_i,"true")
         abc = Product.find_by id: p_id
        flash[:notice_1] = "Item added to the cart: "+abc.Name
      else
        flash[:notice_1] = "Select Item to drop in the cart. None Selected"
      end
        redirect_to '/company'
    end   
  end
  
  def modify_cart
    begin
        p_id = params[:compny]
        user_cart_data = UserCart.where user_id: current_user.id
        item_remove = user_cart_data.find_by product_id: p_id
        if item_remove!=nil
          item_remove.destroy
        end
        redirect_to '/final_cart'
    end
  end
  
  def final_cart
    product_cart = UserCart.where user_id: current_user.id
    len = product_cart.length
    $i =0
    $j =0
    @arr =[]
    @product =[]
    @product_id =[]
    @company =[]
    @length =[]
    while $i < len
     prod_row = Product.where id: product_cart[$i].product_id
     @arr.push(prod_row[0])
     $i+=1
    end
    len = product_cart.length
    while $j < len
      if @arr[$j]!=nil
        @product.push(@arr[$j].Name)
        @company.push(@arr[$j].Company_Name)
        @product_id.push(@arr[$j].id.to_i)
        @length.push($j)
      end
     $j+=1
    end
    render 'final_cart'
  end
  
  def product_category
      if params[:product_line]==nil
        flash[:notice] = "Select one of the below products. None selected"
        redirect_to '/product_line'
        return
      end
      p_l = ProductLine.find_by Name: params[:product_line]
      if p_l==nil
         flash.now[:notice] = "Data not present in Data base for "+params[:product_line]
         render 'product_line'
      else
        product_catgory = ProductCategory.where product_line_id: p_l.id
        len = product_catgory.length
        $i =0
        @arr =[]
        while $i < len.to_i do
          @arr.push( product_catgory[$i].Name.to_s)
          $i+=1
        end
	      session[:product_category_link] = request.url if request.get?
	      session[:product_category] = nil
	      session[:product_category_arr] = @arr
        render 'product_category'
      end
  end

 def company
      if params[:product_category] != nil 
        p_l = ProductCategory.find_by Name: params[:product_category]
        session[:product_category] = p_l
        p_l_id = p_l["id"]
      elsif params[:product_category] == nil and session[:product_category] ==nil
        flash.now[:notice_4] = "Select one of the following product lines. None selected"
        @arr = session[:product_category_arr]
        render 'product_category'
        return
      else
        p_l = session[:product_category]
        p_l_id = p_l["id"]
      end
	    session[:product_link] = request.url if request.get?
      produt_database=Product.where product_category_id: p_l_id
      @Name=[]
      @product_id =[]
      @Company_Name =[]
      @Serving_Size =[]
      @Calories =[]
      @Sat_Fat =[]
      @Sodium =[]
      @Carbs=[]
      @Sugar=[]
      @Fiber =[]
      @Protein =[]
      @Whole_Grain =[]
      @Gluten_Free =[] 
      @Organic =[]
      @Phosphorus =[]
      @Soy =[]
      @Potassium =[]
      @Milk =[]
      @Egg =[]
      @Nut =[]
      @FODMAP =[]
      @Additional_Info =[]
      @id =[]
      user_cncern = ""
      len = produt_database.length
        user_cncern_list = HealthConcern.where user_id: current_user.id
      if user_cncern_list[0].Calorie_Friendly ==1
        user_cncern = "Calorie_Friendly"
      elsif user_cncern_list[0].Heart_Healthy ==1
        user_cncern = "Heart_Healthy"
      elsif user_cncern_list[0].Sodium_Friendly ==1
        user_cncern = "Sodium_Friendly"
      elsif user_cncern_list[0].Carb_Friendly ==1
        user_cncern = "Carb_Friendly"
      elsif user_cncern_list[0].Kidney_Friendly ==1
        user_cncern = "Kidney_Friendly"
      end
      cncern_map = HealthConcernMap.where product_category_id: p_l_id
      if cncern_map[0]==nil
        flash[:notice_2] = "Warning: Concern map is not present in data base for product category item "+p_l["Name"]
        @product = produt_database
      else
        #srt_by = cncern_map[0][user_cncern]
        srt_by = "Calorie_Friendly"
        concern_acronym = {"LS" => "Sodium","LSF" => "Sat_Fat","Lcal" => "Carbs"}
        #@product = produt_database.sort_by { |k| k[concern_acronym[srt_by]]}
        @product = produt_database
      end
    
      render 'company' 
 end
  

  def concerns
  end
  
  def create
    begin
      user_concern_flag = 0
      duplication_error_flag = 0
      if params[:concerns][:calorie_friendly] == "1"
        if user_concern_flag==0
          user_concern_flag = 1
        else
          duplication_error_flag = 1
        end
      end
      if params[:concerns][:heart_healthy] == "1"
        if user_concern_flag==0
          user_concern_flag = 1
        else
          duplication_error_flag = 1
        end
      end
      if params[:concerns][:sodium_friendly] == "1"
        if user_concern_flag==0
          user_concern_flag = 1
        else
          duplication_error_flag = 1
        end
      end
      if params[:concerns][:carb_friendly] == "1"
        if user_concern_flag==0
          user_concern_flag = 1
        else
          duplication_error_flag = 1
        end
      end
      if params[:concerns][:kidney_friendly] == "1"
        if user_concern_flag==0
          user_concern_flag = 1
        else
          duplication_error_flag = 1
        end
      end
      if duplication_error_flag == 1
        flash.now[:notice_3] = "select any one of the concern. More than one is Selected"
        render 'concerns'
        return
      elsif user_concern_flag==0
        flash.now[:notice_3] = "select any one of the concern. None is Selected"
        render 'concerns'
        return
      end
      HealthConcern.update_table(current_user.id,params[:concerns][:calorie_friendly],params[:concerns][:heart_healthy],params[:concerns][:sodium_friendly],params[:concerns][:carb_friendly],params[:concerns][:kidney_friendly])
      rescue Exception => e
      flash[:danger] = e.message
      redirect_to 'https://google.com/'
    else
      flash[:success] = "User Concerns updated"
	    session[:product_line_link] = '/product_line'
      redirect_to '/product_line'
    end
  end
  
  def show
    render 'concerns'
  end
  
  def import
    begin
      HealthConcernMap.import(params[:file])
    rescue Exception => e
      flash[:danger] = e.message
      redirect_to 'https://google.com/'
    else
      flash[:success] = "File Imported"
      redirect_to health_concerns_concerns_path
    end
  end
  
  private
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
  end
    
  def is_admin

        redirect_to(root_url) unless current_user.Admin?
  end
end

app/helpers/health_concerns_helper.rb
module HealthConcernsHelper
end

app/views/health_concerns/company.html.erb
<div id="containerC">

            <div id="topDivC">
                <h1 class="divText" id="title">Product</h1> 
                <div id="navigationBar"> 
                <div id="cart">
                    <%= link_to "My Cart", final_cart_path %>
                </div>
                    <%= csrf_meta_tags %>
                <div id="logout">
                    <%= link_to "Log Out", logout_path, method: "delete" %>
                </div>
                <div id="productcat">
                    <%= link_to "Grocery Products", session[:product_category_link] %>
                </div>
                <div id="productline">
                    <%= link_to "Product Line", session[:product_line_link] %>
                </div>
                <div id="concernslink">
                    <%= link_to "Medical Concerns", health_concerns_concerns_path %>
                </div>
                </div>
                <p id="itemincart"><%= flash[:notice_1] %></p>
                <p id="companyalert"><%= flash[:notice_2] %></p>
            </div>

            <table id="bottomDivC" align ="center" class="sortable">
                <% 
                    temp = params[:product_category]
                    params[:calorieSort] = true
                    def changeCalorieSort(truthValue)
                        if(truthValue == false)
                            calorieSort = false
                        else
                            calorieSort = true
                        end
                    end
                %>
                <%= form_tag("/cart", method: "get") do %>
                <thead>
                    <tr id="labels">
                        <th id="radioLabel"><p class="labelText"></p></th>
                        <th id="nameLabel"><p class="otherLabels">Name</p></th>
                        <!--<div id="caloriesLabel" class="otherLabels"><p class="labelText">Calories</p></div>-->
                        <th id=caloriesLabel><p class="otherLabels">Calories</p></th>
                        <th id="saturatedFatLabel" class="otherLabels"><p class="labelText">Saturated Fat</p></th>
                        <th id="sodiumLabel" class="otherLabels"><p class="labelText">Sodium</p></th>
                        <th id="carbsLabel" class="otherLabels"><p class="labelText">Carbohydrates</p></th>
                        <th id="sugarLabel" class="otherLabels"><p class="labelText">Sugar</p></th>
                        <th id="fiberLabel" class="otherLabels"><p class="labelText">Fiber</p></th>
                        <th id="proteinLabel" class="otherLabels"><p class="labelText">Protein</p></th>
                        <%#<%= link_to '/company?product_category=' + temp + '&commit=Search', :onclick => "return changeCalorieSort(false)" do %><%#<div id="organicLabel" class="otherLabels"><p class="labelText">Organic</p></div><%end%>
                    </tr>
                </thead>

                    <!--<div id="products">-->
                   
                            <%count = 0%>
                            <% trialarray = {} %>
                            <% @product.each do |key| %>
                                <%#
                                if params[:calorieSort] == true 
                                %>
                                    <%#
                                        
                                        trialarray[a] = @Calories[a]
                                        trialarray = trialarray.sort_by {|_key, value| value}.to_h
                                    %>
                                <%# end %>
                            <%# end %>
                            <%#
                                trialarray.each_key do |key|
                            %>
                                <%if true%>
                                    <tbody>
                                    <tr>
                                        <td>
                                                    <%= radio_button_tag(:compny, key.id.to_s) %>
                                                    <%= label_tag(:compny, "") %>  
                                                
                                            </td>  
                                        <td id="productName"><%= "#{key.Name}" %></td>
                                        <td class="productContents"><%= "#{key.Calories}"%></td>
                                        <td class="productContents"><%= "#{key.Sat_Fat}" %></td>
                                        <td class="productContents"><%= "#{key.Sodium}" %></td>
                                        <td class="productContents"><%= "#{key.Carbs}" %></td>
                                        <td class="productContents"><%= "#{key.Sugar}" %></td>
                                        <td class="productContents"><%= "#{key.Fiber}" %></td>
                                        <td class="productContents"><%= "#{key.Protein}" %></p></td>
                                    </tr> 
                                    </tbody>
                                <%else%>
                                    <div id="productU">
                                        <div id="radioBtnCover">
                                                <div id="radioBtn">
                                                    <%= radio_button_tag(:compny, key.id.to_s) %>
                                                    <%= label_tag(:compny, "") %>  
                                                </div>  
                                            </div>  
                                        <div id="productName"><p><%= "#{key.Name}" %></p></div>
                                        <div class="productContents"><p><%= "#{key.Calories}"%></p></div>
                                        <div class="productContents"><p><%= "#{key.Sat_Fat}" %></p></div>
                                        <div class="productContents"><p><%= "#{key.Sodium}" %></p></div>
                                        <div class="productContents"><p><%= "#{key.Carbs}" %></p></div>
                                        <div class="productContents"><p><%= "#{key.Sugar}" %></p></div>
                                        <div class="productContents"><p><%= "#{key.Fiber}" %></p></div>
                                        <div class="productContents"><p><%= "#{key.Protein}" %></p></div>
                                    </div>
                                <% end %>
                                <%count = count + 1%>
                                
                            <% end %>

                            <!--
                    
                            <% @id.each do |a| %>
                                <div id="product">
                                    <div id="productSubContainer">
                                        <p><b>Product : <%= "#{@Name[a]}" %></b></p>
                                        <p><b>Company : <%= "#{@Company_Name[a]}" %></b></p>
                                        <p>
                                            Serving_Size : <%= "#{@Serving_Size[a]}"%>     Calories : <%= "#{@Calories[a]}"%>     Sat_Fat : <%= "#{@Sat_Fat[a]}" %> Sodium : <%= "#{@Sodium[a]}" %>     Carbs : <%= "#{@Carbs[a]}" %>     Sugar : <%= "#{@Sugar[a]}" %>
                                        </p>
                                        <p>
                                            Fiber : <%= "#{@Fiber[a]}" %>     Protein : <%= "#{@Protein[a]}" %>     Whole_Grain : <%= "#{@Whole_Grain[a]}" %> Gluten_Free : <%= "#{@Gluten_Free[a]}" %>     Organic : <%= "#{@Organic[a]}" %>     Phosphorus : <%= "#{@Phosphorus[a]}" %> 
                                        </p>
                                        <p>
                                            Soy : <%= "#{@Soy[a]}" %>     Potassium : <%= "#{@Potassium[a]}" %>     Milk : <%= "#{@Milk[a]}" %> Egg : <%= "#{@Egg[a]}" %>     Nut : <%= "#{@Nut[a]}" %>     FODMAP : <%= "#{@FODMAP[a]}" %>
                                        </p>
                                    </div>
                                    <div id="radioBtnContainer">
                                        <div id="radioBtn">
                                        <%= radio_button_tag(:compny, @product_id[a].to_s) %>
                                        <%= label_tag(:compny, "") %>
                                        </div>
                                    </div>
                                     
                                </div> 
                                
                                
                            <% end %>-->

                        </table>
                        <div id="select"><%= submit_tag("Select") %></div>
                        
                    </div>
                <% end %>
                
            
            

</div>

app/views/health_concerns/concerns.html.erb
<div id="containerHC">

    <div id="topDivHC">
      <h1 class="divText" class="jumbotron">Select Your Primary Medical Concern</h1>
      <div id="navigationBar"> 
      <div id="cart">
          <%= link_to "My Cart", final_cart_path %>
      </div>
          <%= csrf_meta_tags %>
      <div id="logout">
          <%= link_to "Log Out", logout_path, method: "delete" %>
      </div>
    </div>
    </div>

    <div id="middleDivHC">
              <p id="selconcerns"><%= flash.now[:notice_3] %></p>
              <%= form_for :concerns do |f| %>

                  <div id="centerOfPageContainerHC">

                    <div id="topConcerns">
                      
                      <!--URL "/health_concerns/concerns" goes to URL "/product_line-->
                      
                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :sodium_friendly, "...:", class: "label" do %>
                            <%#<div id="picDiv"> <img src=<%=image_url('concerns/salt.png')%><%# alt="..." id="image">  </div>%>
                            <%= link_to image_tag("concerns/salt.png"), "/product_line", params: {:concerns => {:sodium_friendly => 1}} %>
                            
                          </div>

                          <div id="labelDiv">
                            <%#<%= f.check_box :sodium_friendly, class: "checkbox", id: "ck"%>
                            <%= label_tag(:sodium_friendly, "Sodium Friendly") %>
                            <%#<h5>Blood Pressure<br>Friendly</h5>%>
                          </div>
                          <% end %>
                      </div>
                  


                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :heart_healthy, "...:", class: "label" do %> <!--class: "col-xs-12 control-label btn btn-concerns img-check"-->
                            <%# <div id="picDiv"><img src=<%=image_url('concerns/Droplet.png')#><%# alt="..." class="img-responsive"></div> %>
                            <%= link_to image_tag("concerns/Droplet.png"), "/product_line", params: {:concerns => {:heart_healthy => 1}} %>
                          </div>

                          <div id="labelDiv">
                            <%#<%= f.check_box :heart_healthy, class: "checkbox", id: "ck" %><%#  <!-- class: "form-control"-->%>
                            <%#<h5>Cholesterol<br>Friendly</h5>%>
                            <%= label_tag(:heart_healthy, "Cholesterol Friendly") %>
                          </div>
                          <% end %>
                      </div>
                  



                      <div id="outerDiv">
                          <div id="picOuterDiv">
                            <%= f.label :calorie_friendly, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/fork.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/fork.png"), "/product_line", params: {:concerns => {:calorie_friendly => 1}} %>
                          </div>

                          <div id="labelDiv">
                            <%#<%= f.check_box :calorie_friendly, class: "checkbox", id: "ck" %>
                            <%= label_tag(:calorie_friendly, "Calorie Friendly") %>
                            <%#<h5>Calorie<br>Friendly</h5>%>
                          </div>
                          <% end %>
                      </div>
                  


                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :carb_friendly, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/fodmap.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/fodmap.png"), "/product_line", params: {:concerns => {:carb_friendly => 1}} %>
                          </div>

                          <div id="labelDiv">
                            <%#<%= f.check_box :carb_friendly, class: "checkbox", id: "ck" %>
                            <%= label_tag(:carb_friendly, "Carb Friendly") %>
                            <%#<h5>IBS<br>Friendly</h5>%>
                          </div>
                          <% end %>
                      </div>
                  

                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :kidney_friendly, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/renaldisease.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/renaldisease.png"), "/product_line", params: {:concerns => {:kidney_friendly => 1}} %>
                          </div>
                          <div id="labelDiv">
                            <%#<%= f.check_box :kidney_friendly, class: "checkbox", id: "ck" %>
                            <%= label_tag(:kidney_friendly, "Kidney Friendly") %>
                            <%#<h5>Kidney<br>Friendly</h5>%>
                          </div>
                        <% end %>
                      </div>


                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :diabetes_friendly, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/Down.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/Down.png"), "/product_line", params: {:concerns => {:diabetes_friendly => 1}} %>
                          </div>
                          <div id="labelDiv">
                            <%#<%= f.check_box :diabetes_friendly, class: "checkbox", id: "ck" %>
                            <%= label_tag(:diabetes_friendly, "Diabetes Friendly") %>
                            <%#<h5>Diabetes<br>Friendly</h5>%>
                          </div>
                        <% end %>
                      </div>

                    </div>



                    <div id="bottomConcerns">

                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :gluten_free, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/glutenfree.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/glutenfree.png"), "/product_line", params: {:concerns => {:gluten_free => 1}} %>
                          </div>
                          <div id="labelDiv">
                            <%#<%= f.check_box :gluten_free, class: "checkbox", id: "ck" %>
                            <%= label_tag(:gluten_free, "Gluten Free") %>
                            <%#<h5>Gluten<br>Free</h5>%>
                          </div>
                        <% end %>
                      </div>

                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :soy_free, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/soyfree.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/soyfree.png"), "/product_line", params: {:concerns => {:soy_free => 1}} %>
                          </div>
                          <div id="labelDiv">
                            <%#<%= f.check_box :soy_free, class: "checkbox", id: "ck" %>
                            <%= label_tag(:soy_free, "Soy Free") %>
                            <%#<h5>Soy<br>Free</h5>%>
                          </div>
                        <% end %>
                      </div>

                        <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :dairy_free, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/milkfree.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/milkfree.png"), "/product_line", params: {:concerns => {:dairy_free => 1}} %>
                          </div>
                          <div id="labelDiv">
                            <%#<%= f.check_box :dairy_free, class: "checkbox", id: "ck" %>
                            <%= label_tag(:dairy_free, "Diary Free") %>
                            <%#<h5>Dairy<br>Free</h5>%>
                          </div>
                        <% end %>
                      </div>

                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :egg_free, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/eggfree.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/eggfree.png"), "/product_line", params: {:concerns => {:egg_free => 1}} %>
                          </div>
                          <div id="labelDiv">
                            <%#<%= f.check_box :egg_free, class: "checkbox", id: "ck" %>
                            <%= label_tag(:egg_free, "Egg Free") %>
                            <%#<h5>Egg<br>Free</h5>%>
                          </div>
                        <% end %>
                      </div>

                      <div id="outerDiv">
                        
                          <div id="picOuterDiv">
                            <%= f.label :nut_free, "...:", class: "label" do %>
                            <%#<div id="picDiv"><img src=<%=image_url('concerns/nutfree.png')%><%# alt="..." class="img-responsive"></div>%>
                            <%= link_to image_tag("concerns/nutfree.png"), "/product_line", params: {:concerns => {:nut_free => 1}} %>
                          </div>
                          <div id="labelDiv">
                            <%#<%= f.check_box :nut_free, class: "checkbox", id: "ck" %>
                            <%= label_tag(:nut_free, "Nut Free") %>
                            <%#<h5>Nut<br>Free</h5>%>
                          </div>
                        <% end %>
                      </div>

                    <%#</div>%>

                    <%#<div id="startShopping">
                      <%= f.submit 'Start Shopping', :class => 'btn btn-primary center col-xs-2 col-xs-offset-5 margin-tb-t', :id => 'submitButton' %>
                
                    <%#</div>%>

                  <%#</div>%>
              <% end %>


    </div>


    <div id="bottomDivHC"></div>
</div>

app/views/health_concerns/final_cart.html.erb
<div id="containerFC">

			<div id="topDivFC">
				  <h1 class="divText">Shopping Cart</h1> 
			      <div id="navigationBar"> 
			      <div id="cart">
			          <%= link_to "My Cart", final_cart_path %>
			      </div>
			          <%= csrf_meta_tags %>
			      <div id="logout">
			          <%= link_to "Log Out", logout_path, method: "delete" %>
			      </div>
				  <div id="productcat">
                    <%= link_to "Grocery Products", session[:product_category_link] %>
                  </div>
                  <div id="productline">
                    <%= link_to "Product Categories", session[:product_line_link] %>
                  </div>
                  <div id="productWhat">
                    <%= link_to "Products", session[:product_link] %>
                  </div>
                  <div id="concernslink">
                      <%= link_to "Medical Concerns", health_concerns_concerns_path %>
                  </div>
                
			    </div>
		    </div>


        <div id="bottomDivFC">
            <%= form_tag("/modify_cart", method: "get") do %>
                <div id="products">
                
                    <% @length.each do |a| %>

                        <div id="product">
                            <div id="productSubContainerF">
                                <p><b>Product</b> : <%= "#{@product[a]}" %></p>
                                <p><b>Company</b> : <%= "#{@company[a]}" %></p>
                            </div>

                            <div id="radioBtnAndLable">
                                <%= radio_button_tag(:compny, @product_id[a]) %>
                                <%= label_tag(:compny, "Remove", :class=>'remove') %>
                            </div>

                        </div>
                    <% end %>
                    
                    <div="select" id="updateCart"><%= submit_tag("Update Cart") %></div>
                    <div id="spaceBelow"></div>
                </div>
            <% end %>
        </div>

</div>